name: Deploy TraceSync Hub
on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          # Construir Hub
          cd tracesync-hub && npm install && npm run build && cd ..
          # Construir Microapp
          cd chamberInventoryMP && npm install && npm run build && cd ..

      - name: Deploy Hub to Root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tracesync-hub/dist
          destination_dir: .
          force_orphan: true # <--- ESTO ES LA CLAVE: Borra el historial anterior

      - name: Deploy Microapp to Subdirectory
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./chamberInventoryMP/dist
          destination_dir: chamberInventoryMP
